theme: jekyll-theme-minimal
title: Nick Clarke
description: Cleantech Enthusiast
logo: https://avatars0.githubusercontent.com/u/2177320
show_social: yes
site.linkedin_url: https://www.linkedin.com/in/nickolasclarke/
site.ucb_url: https://erg.berkeley.edu/people/nick-clarke/
