theme: jekyll-theme-minimal
title: Nick Clarke
description: Climate-focused technologist with a background in software development, machine learning, and technical product management building IoT solutions in electric vehicle grid integration, real-time energy analysis and optimization.
logo: https://avatars0.githubusercontent.com/u/2177320
show_social: yes
linkedin_url: https://www.linkedin.com/in/nickolasclarke/
ucb_url: https://erg.berkeley.edu/people/nick-clarke/
